"""removed message node specific fields

Revision ID: 0ee9dbc73d9e
Revises: bdaa7a5d6109
Create Date: 2025-07-23 12:19:03.629271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee9dbc73d9e'
down_revision: Union[str, None] = 'bdaa7a5d6109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('workflow_nodes', 'message_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_nodes', sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
