"""Added chattermate AI model

Revision ID: 520df92643e3
Revises: 85364d188f15
Create Date: 2025-03-28 23:27:11.906265

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '520df92643e3'
down_revision: Union[str, None] = '85364d188f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new temporary type with the new value
    op.execute("ALTER TYPE aimodeltype ADD VALUE IF NOT EXISTS 'CHATTERMATE'")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL does not support removing enum values
    # We can only create a new enum without the value and replace the old one
    pass
    # ### end Alembic commands ###
