"""added wlecome header and title 

Revision ID: 7991b4fc00d8
Revises: 6885c9f36712
Create Date: 2025-07-27 16:11:49.392307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7991b4fc00d8'
down_revision: Union[str, None] = '6885c9f36712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('agent_customizations', sa.Column('welcome_title', sa.String(), nullable=True))
    op.add_column('agent_customizations', sa.Column('welcome_subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_customizations', 'welcome_subtitle')
    op.drop_column('agent_customizations', 'welcome_title')


    # ### end Alembic commands ###
