"""removed node specific fields

Revision ID: bdaa7a5d6109
Revises: dd0e5ceefe4b
Create Date: 2025-07-23 12:06:47.901308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdaa7a5d6109'
down_revision: Union[str, None] = 'dd0e5ceefe4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint('workflow_nodes_model_id_fkey', 'workflow_nodes', type_='foreignkey')
    op.drop_column('workflow_nodes', 'action_type')
    op.drop_column('workflow_nodes', 'form_fields')
    op.drop_column('workflow_nodes', 'model_id')
    op.drop_column('workflow_nodes', 'system_prompt')
    op.drop_column('workflow_nodes', 'condition_expression')
    op.drop_column('workflow_nodes', 'wait_until_condition')
    op.drop_column('workflow_nodes', 'action_config')
    op.drop_column('workflow_nodes', 'temperature')
    op.drop_column('workflow_nodes', 'wait_duration')
    op.drop_column('workflow_nodes', 'transfer_rules')
    op.drop_column('workflow_nodes', 'landing_page_content')
    op.drop_column('workflow_nodes', 'landing_page_heading')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_nodes', sa.Column('landing_page_heading', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('landing_page_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('transfer_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('wait_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('action_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('wait_until_condition', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('condition_expression', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('form_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflow_nodes', sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('workflow_nodes_model_id_fkey', 'workflow_nodes', 'ai_configs', ['model_id'], ['id'])

    # ### end Alembic commands ###
