"""Agent created date added

Revision ID: e252efacd083
Revises: 9a01e6b653b2
Create Date: 2025-07-09 10:30:11.970669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e252efacd083'
down_revision: Union[str, None] = '9a01e6b653b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'created_at')

    # ### end Alembic commands ###
