"""add jira agent config

Revision ID: e65e1b8e7e3c
Revises: 30caca239191
Create Date: 2025-03-06 21:51:54.214580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65e1b8e7e3c'
down_revision: Union[str, None] = '30caca239191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jira_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=True),
    sa.Column('issue_type_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_jira_configs_agent_id'), 'agent_jira_configs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_jira_configs_id'), 'agent_jira_configs', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_agent_jira_configs_id'), table_name='agent_jira_configs')
    op.drop_index(op.f('ix_agent_jira_configs_agent_id'), table_name='agent_jira_configs')
    op.drop_table('agent_jira_configs')
    # ### end Alembic commands ###
