"""added user id in rating table

Revision ID: fa04f644fc0c
Revises: 186c65ae9406
Create Date: 2025-03-05 15:38:12.395283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa04f644fc0c'
down_revision: Union[str, None] = '186c65ae9406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('ratings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'user_id')

    # ### end Alembic commands ###
